<p>Untranslated messages: <?php echo count($translator->untranslated); ?>, loaded resources <?php echo $resourcesCount; ?></p>
<div class="tracy-inner">
  <div id="resolvedLanguage">
    <h1>Resolved language</h1>
    <table>
      <tr><td><?php echo $loader->getResolverName(); ?></td><td><?php echo $loader->lang; ?></td></tr>
    </table>
  </div>
  <br/>
  <div id="resources">
    <h1>Loaded resources</h1>
    <table>
      <tr><th>Domain</th><th>Filename</th></tr>
      <?php foreach($loader->getResources() as $domain => $files) {
        foreach($files as $filename) {
          echo "<tr><td>$domain</td><td>" . \Tracy\Helpers::editorLink($filename) . "</td></tr>";
        }
      }
      ?>
    </table>
  </div>
  <div id="untranslated">
    <?php if(count($translator->untranslated)) echo "<h1>Untranslated messages</h1>"; ?>
    <?php foreach($translator->untranslated as $message) {
      echo "<p>$message</p>";
    }
    ?>
  </div>
</div>